---
title: "Weekly Log"
author: "Sushant"
date: "2025-10-02"
output:
  pdf_document: default
  html_document: default
---

<font size="5">**Week 1 Reading Notes:**</font>   
<font size="3">***Book: Using Geochemical Data (Rollinson and Pease)***</font>  
1. Normalising values can be chosen from 2 sets:   
i) CI chondrites   
ii) Ordinary chrondrites (volatile free, tend to have higher values).  
Therefore, it is important to cite the right data set. See pg.130 for dataset. 

Shale normalisation is used for upper crust sediments while Chondrite normalisation will be used in our project since we want to compare igneous rocks to primitive solar system. 

2. REE in minerals in Igneous Rocks:  
i)**Feldspars**: low concentration, but when in felsic rocks, Eu anomaly is +ve   
ii)**Olivine**: very low concentration, unlikely to fractionate REE while fractionation/partial melting.   
iii)**Pyroxenes**: orthopyroxenes have lower REE than clinopyroxenes. In mafic rocks, REE are mostly present in clinopyroxene. Pyroxenes have small -ve anomalies but maybe be higher in clinopyroxenes.  
iv)**Hornblende**: enriched in middle REE, have higher concentration of HREE that forms a U-shaped REE pattern in melt.   
v)**Garnet**: high abundance of HREE to the extent that they are compatible whilst LREE aren't.    
vi)**Muscovite**: enriched in REE, especially in felsic rocks. -ve Eu anomaly.    
vii)**Biotite**: less enriched in REE, -ve Eu anomaly.   
viii)**Zircon**: deplete a melt in HREE.     
ix)**Other accessory phases**: strong influence on REE pattern even if they have low abundance. They have high partition coefficients which result in disproportionate influence and depletion in REE.      

3. Multi-element Diagrams (MeD):  
i)**Chondrite-Normalised MeD**: advantageous since it uses directly measured values instead of calculated ones. It might not be very suitable for sediment and evolved igneous rocks ( do they mean metamorphic?). They have plotted REE and and some other trace elements in order of increasing mantle compatibility on log scale using normalised values with McDonough and and Sun(1995) and Palme and ONeil(2014) as reference values.  
ii)In evolved igenous rocks, anomalies may be controlled by specific mineral as mentioned in point 2 above where LREE are controlled by allanite and HREE by garnet. 

<font size="3">***Research Paper- Wall (2012) :"Rare Earth Elements: Minerals, Mines, Magnets"***</font>

<font size="3">***Research Paper- O'Neill(2016) :"The Smoothness and Shapes of Chondrite-normalized Rare Earth Element Patterns in Basalts"***</font>

<font size="5">***Code for Week 1: Spider Plot Function***</font>

In a Spider Diagram, we will be representing the log normalised concentrations of Rare Earth Elements. The following Elements will be plotted: 
La-Lanthanum, Ce- Cerium, Pr- Praseodymium, Nd- Neodymium, Pm- Promethium, Sm- Samarium, Eu- Europium, Gd- Gadolinium,, Tb- Terbium, Dy- Dysprosium, Ho- Holmium, Er- Erbium, Tm- Thulium, Yb- Ytterbium, Lu- Lutetium 
```{r}
#downloading dataset
setwd("~/Desktop/MSci Project /Rock data for Spider Diagrams")
adakite <- read.csv(file = 'ADAKITE.csv')
ref <- read.csv(file='normalised values.csv')
# gathering REE data from sample
ree_sample1 <- as.numeric(adakite[19, 119:132])
#
ree_ref <- as.numeric(ref[3:16, 14]) #column 4,5 dont work

#this is a function for plotting spider plots for REE data
plot_spider <- function(samples,reference_values,logscale=TRUE,colors=NULL,main= "Spider Plot for Normalised REE Values",xlab="Rare Earth Elements",ylab ="Normalised values")
{
  # these are the REE we will be covering generally
  REE_symbols <-  c("La","Ce","Pr","Nd","Sm","Eu","Gd","Tb","Dy","Ho","Er","Tm","Yb","Lu")
  # normalising values of samples with the reference set
  normalised_values <- lapply(samples,function(s1) as.numeric(s1)/as.numeric(reference_values))
  #axis range
  ymin <- if (logscale) min(unlist(normalised_values), na.rm = TRUE) else 0
  ymax <- max(unlist(normalised_values), na.rm = TRUE)
  # generate plot 
  plot(1:length(reference_values),normalised_values[[1]],type="b",xaxt="n",,xlab="Rare Earth Elements",ylab ="Concentration",log = 'y',ylim = c(ymin, ymax))
  axis(1,at=1:length(reference_values),labels = REE_symbols)
  grid(nx=NULL, ny=NULL,col="gray",lwd=1)
  abline(h=1,col="black",lwd=3)
  
  # generate other plots 
   if(length(normalised_values)>1)
   { 
       for(i in 2:length(normalised_values))
       {
         lines(1:length(normalised_values),normalised_values[[i]],type="b")
       }
   }
}
samples <- list(ree_sample1)

plot_spider(samples, ree_ref,main = "REE Spider Diagram (Sample 19, Ref Col 14)")
```










